title: "Nathalie Uwamahoro - Teaching Portfolio"
description: "Teaching Portfolio showcasing my teaching experience, materials, and reflections."

# IMPORTANT: Change baseurl to your repository name, prefixed with a slash
baseurl: "/teaching_portfolio"
url: "https://nathalie-uwamahoro.github.io"  # No trailing slash

theme: minima
markdown: kramdown

author:
  name: "Nathalie Uwamahoro"
  email: "nuwamaho@syr.edu"
  social:
    linkedin: "https://www.linkedin.com/in/nathalie-uwamahoro"
    my_website: "https://Nathalie-Uwamahoro.github.io"

navigation:
  - title: "Home"
    url: "/"
  - title: "Personal Statement"
    url: "/personal-statement/"
  - title: "CV"
    url: "/cv/"
  - title: "Teaching"
    url: "/teaching/"
  - title: "Student Evaluations"
    url: "/student-evaluations/"
  - title: "Additional Materials"
    url: "/additional-materials/"
