title: "Nathalie Uwamahoro"
description: "PhD Candidate in Electrical and Computer Engineering"
author:
  name: "Nathalie Uwamahoro"
  email: "nuwamaho@syr.edu"
  social:
    github: "https://github.com/naty1"
    linkedin: "https://www.linkedin.com/in/nathalie-uwamahoro"
    # scholar: "https://scholar.google.com/citations?user=YourGoogleScholarID"

baseurl: "" # Leave this empty for GitHub Pages
url: "https://Nathalie-Uwamahoro.github.io" # Replace with your GitHub Pages URL
theme: minima # Or use another theme

defaults:
  - scope:
      path: ""
    values:
      navigation:
        - title: "Home"
          url: "/home/"
        - title: "Projects"
          url: "/projects/"
        - title: "Publications"
          url: "/publications/"
        - title: "CV"
          url: "/cv/"
