title: "Nathalie Uwamahoro - Teaching Portfolio"
description: "Teaching Portfolio showcasing my teaching experience, materials, and reflections."

# For a USER site (teaching-portfolio.github.io), set baseurl to an empty string:
baseurl: ""

# The URL should match your new GitHub username (account name) + .github.io
# with no trailing slash:
url: "https://teaching-portfolio.github.io"

theme: minima
markdown: kramdown

author:
  name: "Nathalie Uwamahoro"
  email: "nuwamaho@syr.edu"
  social:
    linkedin: "https://www.linkedin.com/in/nathalie-uwamahoro"
    # website: "https://Nathalie-Uwamahoro.github.io"

navigation:
  - title: "Home"
    url: "/"
  - title: "Personal Statement"
    url: "/personal-statement/"
  - title: "CV"
    url: "/cv/"
  - title: "Teaching"
    url: "/teaching/"
  - title: "Student Evaluations"
    url: "/student-evaluations/"
  - title: "Additional Materials"
    url: "/additional-materials/"
